# frozen_string_literal: true

source "https://rubygems.org"

gem "github-pages", :group => :jekyll_plugins, :path => "../../"
gem "jekyll_test_plugin_malicious"

# Whitelisted plugins not included in runtime dependencies.
gem "jekyll-octicons", :group => :jekyll_plugins
