#!/bin/bash -ex

(git branch | grep -q '* master') || {
  echo "Only release from the master branch."
  exit 1
}

VERSION_FILE="./lib/github-pages/version.rb"
OLD_VERSION=$(curl "https://rubygems.org/api/v1/versions/github-pages/latest.json" | jq -r .version)
NEW_VERSION=$(expr $OLD_VERSION + 1)
echo -e "module GitHubPages\n  VERSION = $NEW_VERSION\nend" > $VERSION_FILE
git add $VERSION_FILE
git commit -m "Bump :gem: to v$NEW_VERSION"
git push origin master

script/release
