#!/bin/sh

set -ex

# Set the ruby version in the Action definition matrix.
: "${RUBY_VERSION:="3.2"}"

docker build --build-arg "RUBY_VERSION=$RUBY_VERSION" -t github-pages .
docker run --rm --workdir /src/gh/pages-gem github-pages script/cibuild
