#!/bin/sh
# Test that all dependencies resolve

set -ex

bundle exec jekyll --version
bundle exec rspec

rm -Rf ./test-site
bundle exec jekyll new test-site
cd test-site && bundle exec jekyll build --trace
