#!/usr/bin/env ruby
# Push the Ruby Gem to rubygems.org

require "rubygems"
spec = Gem::Specification::load("github-pages.gemspec")

system 'script/build'

puts "Pushing the Gem to rubygems.org..."
system "gem push github-pages-#{spec.version}.gem"
puts ":gem: :gem: :gem:!"