#!/bin/sh
# Test that the default Jekyll site builds

set -e

rm -Rf ./test-site
bundle exec jekyll new test-site

cd test-site
echo 'source "https://rubygems.org"' > Gemfile
echo 'gem "github-pages", path: "../", group: :jekyll_plugins' >> Gemfile
bundle install

theme_name="$1"
if [ -n "$theme_name" ]; then
  echo "theme: $theme_name" >> _config.yml
fi

echo "Using $(bundle exec github-pages --version)"
echo "Using $(bundle exec jekyll --version)"
bundle exec jekyll build --trace --verbose

grep --quiet "Your awesome title" ./_site/index.html
echo "Site built!"

cd ..
rm -Rf ./test-site
