#!/bin/sh
# Test that the default Jekyll site builds

set -ex

rm -Rf ./test-site
bundle exec jekyll new test-site

cd test-site && bundle install
bundle exec jekyll build --trace --verbose

grep --quiet "Your awesome title" ./_site/index.html

cd ..
rm -Rf ./test-site
